# .github/workflows/main_dietitian-be.yml  (patched)
name: Deploy backend → Azure (dietitian-be)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # ✅ repo-root is already .../dietitian_web
    defaults:
      run:
        working-directory: backend       # <-- just backend

    steps:
      - uses: actions/checkout@v4

      # (optional) local tests
      - name: Install deps for local checks
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # package only the backend folder
      - name: Zip backend for Azure
        run: |
          zip -r ${{ github.workspace }}/backend.zip . \
                 -x "venv/**" "__pycache__/**"

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: dietitian-be
          slot-name: Production
          package: ${{ github.workspace }}/backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E89ED6E4A48748E299AEA7F7A5E3AD42 }}
