# .github/workflows/main_dietitian-be.yml  (patched)
name: Deploy backend → Azure (dietitian-be)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # ✅ repo-root is already .../dietitian_web
    defaults:
      run:
        working-directory: backend       # <-- just backend

    steps:
      - uses: actions/checkout@v4

      # (optional) local tests
      - name: Install deps for local checks
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # package only the backend folder
      - name: Zip backend for Azure
        run: |
          zip -r ${{ github.workspace }}/backend.zip . \
                 -x "venv/**" "__pycache__/**"

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: dietitian-be
          slot-name: Production
          package: ${{ github.workspace }}/backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E89ED6E4A48748E299AEA7F7A5E3AD42 }}

      - name: Configure startup command
        uses: azure/appservice-settings@v1
        with:
          app-name: dietitian-be
          app-settings-json: |
            [
              {
                "name": "WEBSITES_PORT",
                "value": "8000"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "0"
              }
            ]
          startup-command: "cd /home/site/wwwroot && python -m pip install --upgrade pip && pip install -r requirements.txt && gunicorn --bind 0.0.0.0:8000 backend:app"

# Note: Make sure to configure these environment variables in Azure App Service:
# - supabaseUrl
# - supabaseKey  
# - AZURE_TRANSLATOR_ENDPOINT
# - AZURE_TRANSLATOR_KEY
# - AZURE_TRANSLATOR_REGION
# - AZURE_OPENAI_API_BASE
# - AZURE_OPENAI_API_KEY
# - AZURE_OPENAI_DEPLOYMENT (optional, defaults to "obi1")