name: Build & deploy backend → Azure (dietitian-be)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # work inside ./backend
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      # ── optional local tests ──
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # ──────────────────────────

      # 1️⃣  copy requirements.txt one level up
      - name: Stage deployment zip
        run: |
          cp requirements.txt ..            # now exists at repo root
          cd ..                             # repo root
          zip -r backend.zip backend        # keep folder prefix
          zip -u backend.zip requirements.txt

      - name: Debug – show zip contents
        run: unzip -l backend.zip | head

      - uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with: { name: backend-artifact }

      - run: ls -l backend.zip              # sanity check

      - uses: azure/webapps-deploy@v3
        with:
          app-name: dietitian-be
          slot-name: Production
          package: backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E89ED6E4A48748E299AEA7F7A5E3AD42 }}
