name: Build & deploy backend → Azure (dietitian-be)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # build runs inside ./backend
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package **backend/** folder
        run: |
          cd ..                       # repo root
          zip -r backend.zip backend  # includes folder prefix

      - name: Show zip content (debug)
        run: unzip -l backend.zip | head

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend.zip           # exact filename

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Verify zip presence (debug)
        run: ls -l backend.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: dietitian-be
          slot-name: Production
          package: backend.zip        # ← must match filename above
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E89ED6E4A48748E299AEA7F7A5E3AD42 }}
