# .github/workflows/main_dietitian-be.yml  (patched)
name: Deploy backend → Azure (dietitian-be)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # (optional) local tests
      - name: Install deps for local checks
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # package only the backend folder contents (not the folder itself)
      - name: Zip backend for Azure
        run: |
          cd backend
          find . -type f -not -path "./venv/*" -not -path "./__pycache__/*" -exec zip ../backend.zip {} \;

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: dietitian-be
          slot-name: Production
          package: ${{ github.workspace }}/backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E89ED6E4A48748E299AEA7F7A5E3AD42 }}

# Note: Make sure to configure these environment variables in Azure App Service:
# - supabaseUrl
# - supabaseKey  
# - AZURE_TRANSLATOR_ENDPOINT
# - AZURE_TRANSLATOR_KEY
# - AZURE_TRANSLATOR_REGION
# - AZURE_OPENAI_API_BASE
# - AZURE_OPENAI_API_KEY
# - AZURE_OPENAI_DEPLOYMENT (optional, defaults to "obi1")
#
# Startup Command to set in Azure App Service:
# python backend.py
#
# App Settings to configure in Azure App Service:
# - WEBSITES_PORT = 8000
# - SCM_DO_BUILD_DURING_DEPLOYMENT = 0
# - WEBSITES_CONTAINER_START_TIME_LIMIT = 1800